### ISSUE TITLE
Best practices for Ruby

### ISSUE THREAD

**Issue by bkaestner** [bkaestner/codewars-rules#8]
Best practices for Ruby are currently missing. They should at least cover the current one in JavaScript, including freeze and other stuff.

**Comment by danielpclark** [comment]
I'd like to help on this.  Don't know if I have time to do a full write up but here are some useful tidbits.

When using Test.assert_equals the only thing I have found fool proof is to use a String as the first parameter.  The assert_equals method simply calls the method `:==` on the first object and passes the second object in as a parameter.  In Ruby it's impossible to tamper with `String#==` as it will simply make the language not work, so using it as the first parameter is fool proof.

``` ruby
def thing
  "foo"
end

Test.assert_equals("foo", thing)
```

The documentation normally lists the thing you want to test as the first parameter, but you should keep in mind that you're actually testing the `:==` method on the first thing rather than just the result.

<h3>Randomness</h3>

There are several ways you can do random testing.

``` ruby
def thing(_)
  "output"
end

# Array pairs
[["input", "output"], ["input2", "output"]].each do |input, output|
  # AB and BA testing is recommended
  Test.assert_equals( thing(input), output )
  Test.assert_equals( output, thing(input) )
end

# Hash test key-value pairs
{"input" => "output", "input2" => "output"}.each do |input, output|
  # AB and BA testing is recommended
  Test.assert_equals( thing(input), output )
  Test.assert_equals( output, thing(input) )
end

# Have all tests in Procs within an Array, shuffle them and run them
[
  ->{ Test.assert_equals( thing(input), "output" ) },
  ->{ Test.assert_equals( "output", thing(input) ) },
  ->{ Test.assert_not_equals( "R2D2", thing(input) ) }
].shuffle.map(&:call)
```

Of course appropriate messages should be included for failing tests.  The test suite permits nice spec formatting. _(excerpt from one of my katas)_

``` ruby
describe "tonk sets" do
  it "negates fallacies" do
    Test.assert_not_equals(get_sets(%w^7h 8h 9h Th Jh Qh^), :none)
  end

  it "evaluates sets of :all" do
    Test.assert_equals(get_sets(%w^7h 8h 9h Th Jh Qh^), :all)
  end
end
```

This will give descriptions for which tests failed.  Depending on how much information you want to give it's a good idea to point to where their code missed something in coverage rather than saying "you gave 32 and 42 was expected".

In Ruby any object that is frozen cannot be tampered with and that includes the Test object provided in CodeWars.com

**Comment by danielpclark** [comment]
In Ruby there are so many ways of doing things.  Here's another idea for randomness.

``` ruby
class MyTests
  def not_a_number
    Test.assert_equals(
      thing("input").is_a?(Fixnum),
      false,
      "The result should not be a number!"
    )
  end
  def is_a_string
    Test.expect(
      thing("input").is_a?(String),
      "thing must return a String!"
    )
  end
  def correct_value
    Test.assert_equals(
      thing("input"),
      "output",
      "The wrong return value was received!"
    )
  end
end

my_tests = MyTests.new
[:correct_value, :is_a_string, :not_a_number].shuffle.each do |test|
  my_tests.send test
end
```

**Comment by bkaestner** [comment]
>  The `assert_equals` method simply calls the method `:==` on the first object and passes the second object in as a parameter.

This brings me to the following question: if one uses the module system (e.g. provide an automatic wrapper around the source and `require` it), can the user still tamper with the operators on a global basis? Or are any changes locally bound to the module?

**Comment by danielpclark** [comment]
Everything in Ruby goes through an ancestry chain.  It will go from the first Object in the ancestry down to the last until it finds the method.  The first Object has it's instance methods evaluated (known as a singleton instance).  Every ancestor is checked up the chain for and instance method by that name.  If none are found by the end then it triggers the first `method_missing` in that chain.

``` ruby
class A
  def fun;      "A-instance"  end
  def self.fun; "A-class"     end
  def singleton_class.fun;    "A-singleton"   end
end

class B < A
  def fun;      "B-instance"  end
  def self.fun; "B-class"     end
  def singleton_class.fun;    "B-singleton"   end
end

module C
  def fun;      "C-instance"  end
  def self.fun; "C-module"    end
  def singleton_class.fun;    "C-singleton"   end
end

class D < B; end

D.ancestors
# => [D, B, A, Object, Kernel, BasicObject]
D.new.fun
# => "B-instance"

B.prepend C
D.ancestors
# => [D, C, B, A, Object, Kernel, BasicObject]
D.new.fun
# => "C-instance"

class D
  undef :fun
end
D.new.fun
#NoMethodError: undefined method `fun' for #<D:0x00000002a79548>
class D
  def fun
    super
  end
end
D.new.fun
# => "C-instance"

module C
  undef :fun
  def fun
    super
  end
end
D.new.fun
# => "B-instance"
```

Most everything can be undefined, redefined, and overridden.  When `:undef` is used it won't call any parent versions of the method.  For that it needs to be redefined with a call to `super`

The reason you can't change `String#==` is because Ruby heavily uses it for it's lexical calculations and that's a core part of Ruby.

**Comment by danielpclark** [comment]
If a person doesn't want an object/class/module tampered with they must call `freeze` on it.  The ancestry chain can't be modified _(although unfrozen ancestors can)_, and nothing else can be modified.

**Comment by danielpclark** [comment]
"can the user still tamper with the operators on a global basis?"

For the most part I don't think there are global "operators", only method calls.  There are very few keywords and they are not tamperable.  The globally available methods are provided by the Kernel module and that is modifiable.

``` ruby
method(:puts).owner
# => Kernel

module Kernel
  def puts *_
    "echo"
  end
end

puts "Hello World!"
# => "echo"
```
